export NECOFS=/opt/necofs
export PATH=$NECOFS/bin${PATH:+:$PATH}
export LIBRARY_PATH=$NECOFS/lib${LIBRARY_PATH:+:$LIBRARY_PATH}
export LD_LIBRARY_PATH=$NECOFS/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export C_INCLUDE_PATH=$NECOFS/include${C_INCLUDE_PATH:+:$C_INCLUDE_PATH}
export PETSC_DIR=$NECOFS
